### ISSUE TITLE
Checklist for 'reformat' PR

### ISSUE THREAD

**Issue by jkbhagatio** [SainsburyWellcomeCentre/aeon_mecha#235]
After merging 'config' (#228) into 'main', we will create another branch called 'reformat', which will contain all the reformatted changes according to the specs in 'config'.

We should make sure the following works / is done before merging 'reformat' into 'main':

- [x] .pre-commit-config.yaml
- [x] build_env_run_tests.yml
- [x] gpt_pr_review.yml
- [x] squash_merge_to_prod.yml
- [x] Update branch protection rules
- [ ] Create docstrings for all modules and functions

**Comment by jkbhagatio** [comment]
> Create docstrings for all modules and functions

This last one will be done in "cleanup" branch
